package main.java.indexfs.serverless;

public class ServerlessIndexFSOperationParameters {
	/**
	 * Operation parameters including operation type, Thrift Key, and inode number
	 */
	
	/**
	 * Operation types. 1: Mknod. 2: Mkdir. 3: Getattr. 4: Flush.
	 */
	public int op_type;
	
	/**
	 * MetaDB key structure generated by Thrift.
	 */
	public KeyInfo_THRIFT key;
	
	/**
	 * Inode number.
	 */
	public long ino;
	
	public ServerlessIndexFSOperationParameters() {
		this.key = new KeyInfo_THRIFT();
	}
}
