/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MetaDBService_H
#define MetaDBService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "indexfs_types.h"

namespace indexfs {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class MetaDBServiceIf {
 public:
  virtual ~MetaDBServiceIf() {}
  virtual void NewFile(const KeyInfo_THRIFT& key) = 0;
  virtual void NewDirectory(const KeyInfo_THRIFT& key, const int16_t zeroth_server, const int64_t inode_no) = 0;
};

class MetaDBServiceIfFactory {
 public:
  typedef MetaDBServiceIf Handler;

  virtual ~MetaDBServiceIfFactory() {}

  virtual MetaDBServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MetaDBServiceIf* /* handler */) = 0;
};

class MetaDBServiceIfSingletonFactory : virtual public MetaDBServiceIfFactory {
 public:
  MetaDBServiceIfSingletonFactory(const boost::shared_ptr<MetaDBServiceIf>& iface) : iface_(iface) {}
  virtual ~MetaDBServiceIfSingletonFactory() {}

  virtual MetaDBServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(MetaDBServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<MetaDBServiceIf> iface_;
};

class MetaDBServiceNull : virtual public MetaDBServiceIf {
 public:
  virtual ~MetaDBServiceNull() {}
  void NewFile(const KeyInfo_THRIFT& /* key */) {
    return;
  }
  void NewDirectory(const KeyInfo_THRIFT& /* key */, const int16_t /* zeroth_server */, const int64_t /* inode_no */) {
    return;
  }
};

typedef struct _MetaDBService_NewFile_args__isset {
  _MetaDBService_NewFile_args__isset() : key(false) {}
  bool key :1;
} _MetaDBService_NewFile_args__isset;

class MetaDBService_NewFile_args {
 public:

  MetaDBService_NewFile_args(const MetaDBService_NewFile_args&);
  MetaDBService_NewFile_args& operator=(const MetaDBService_NewFile_args&);
  MetaDBService_NewFile_args() {
  }

  virtual ~MetaDBService_NewFile_args() throw();
  KeyInfo_THRIFT key;

  _MetaDBService_NewFile_args__isset __isset;

  void __set_key(const KeyInfo_THRIFT& val);

  bool operator == (const MetaDBService_NewFile_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const MetaDBService_NewFile_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MetaDBService_NewFile_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MetaDBService_NewFile_pargs {
 public:


  virtual ~MetaDBService_NewFile_pargs() throw();
  const KeyInfo_THRIFT* key;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MetaDBService_NewFile_result__isset {
  _MetaDBService_NewFile_result__isset() : io_error(false), srv_error(false) {}
  bool io_error :1;
  bool srv_error :1;
} _MetaDBService_NewFile_result__isset;

class MetaDBService_NewFile_result {
 public:

  MetaDBService_NewFile_result(const MetaDBService_NewFile_result&);
  MetaDBService_NewFile_result& operator=(const MetaDBService_NewFile_result&);
  MetaDBService_NewFile_result() {
  }

  virtual ~MetaDBService_NewFile_result() throw();
  IOError io_error;
  ServerInternalError srv_error;

  _MetaDBService_NewFile_result__isset __isset;

  void __set_io_error(const IOError& val);

  void __set_srv_error(const ServerInternalError& val);

  bool operator == (const MetaDBService_NewFile_result & rhs) const
  {
    if (!(io_error == rhs.io_error))
      return false;
    if (!(srv_error == rhs.srv_error))
      return false;
    return true;
  }
  bool operator != (const MetaDBService_NewFile_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MetaDBService_NewFile_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MetaDBService_NewFile_presult__isset {
  _MetaDBService_NewFile_presult__isset() : io_error(false), srv_error(false) {}
  bool io_error :1;
  bool srv_error :1;
} _MetaDBService_NewFile_presult__isset;

class MetaDBService_NewFile_presult {
 public:


  virtual ~MetaDBService_NewFile_presult() throw();
  IOError io_error;
  ServerInternalError srv_error;

  _MetaDBService_NewFile_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MetaDBService_NewDirectory_args__isset {
  _MetaDBService_NewDirectory_args__isset() : key(false), zeroth_server(false), inode_no(false) {}
  bool key :1;
  bool zeroth_server :1;
  bool inode_no :1;
} _MetaDBService_NewDirectory_args__isset;

class MetaDBService_NewDirectory_args {
 public:

  MetaDBService_NewDirectory_args(const MetaDBService_NewDirectory_args&);
  MetaDBService_NewDirectory_args& operator=(const MetaDBService_NewDirectory_args&);
  MetaDBService_NewDirectory_args() : zeroth_server(0), inode_no(0) {
  }

  virtual ~MetaDBService_NewDirectory_args() throw();
  KeyInfo_THRIFT key;
  int16_t zeroth_server;
  int64_t inode_no;

  _MetaDBService_NewDirectory_args__isset __isset;

  void __set_key(const KeyInfo_THRIFT& val);

  void __set_zeroth_server(const int16_t val);

  void __set_inode_no(const int64_t val);

  bool operator == (const MetaDBService_NewDirectory_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    if (!(zeroth_server == rhs.zeroth_server))
      return false;
    if (!(inode_no == rhs.inode_no))
      return false;
    return true;
  }
  bool operator != (const MetaDBService_NewDirectory_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MetaDBService_NewDirectory_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MetaDBService_NewDirectory_pargs {
 public:


  virtual ~MetaDBService_NewDirectory_pargs() throw();
  const KeyInfo_THRIFT* key;
  const int16_t* zeroth_server;
  const int64_t* inode_no;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MetaDBService_NewDirectory_result__isset {
  _MetaDBService_NewDirectory_result__isset() : io_error(false), srv_error(false) {}
  bool io_error :1;
  bool srv_error :1;
} _MetaDBService_NewDirectory_result__isset;

class MetaDBService_NewDirectory_result {
 public:

  MetaDBService_NewDirectory_result(const MetaDBService_NewDirectory_result&);
  MetaDBService_NewDirectory_result& operator=(const MetaDBService_NewDirectory_result&);
  MetaDBService_NewDirectory_result() {
  }

  virtual ~MetaDBService_NewDirectory_result() throw();
  IOError io_error;
  ServerInternalError srv_error;

  _MetaDBService_NewDirectory_result__isset __isset;

  void __set_io_error(const IOError& val);

  void __set_srv_error(const ServerInternalError& val);

  bool operator == (const MetaDBService_NewDirectory_result & rhs) const
  {
    if (!(io_error == rhs.io_error))
      return false;
    if (!(srv_error == rhs.srv_error))
      return false;
    return true;
  }
  bool operator != (const MetaDBService_NewDirectory_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MetaDBService_NewDirectory_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MetaDBService_NewDirectory_presult__isset {
  _MetaDBService_NewDirectory_presult__isset() : io_error(false), srv_error(false) {}
  bool io_error :1;
  bool srv_error :1;
} _MetaDBService_NewDirectory_presult__isset;

class MetaDBService_NewDirectory_presult {
 public:


  virtual ~MetaDBService_NewDirectory_presult() throw();
  IOError io_error;
  ServerInternalError srv_error;

  _MetaDBService_NewDirectory_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MetaDBServiceClient : virtual public MetaDBServiceIf {
 public:
  MetaDBServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MetaDBServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void NewFile(const KeyInfo_THRIFT& key);
  void send_NewFile(const KeyInfo_THRIFT& key);
  void recv_NewFile();
  void NewDirectory(const KeyInfo_THRIFT& key, const int16_t zeroth_server, const int64_t inode_no);
  void send_NewDirectory(const KeyInfo_THRIFT& key, const int16_t zeroth_server, const int64_t inode_no);
  void recv_NewDirectory();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MetaDBServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<MetaDBServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (MetaDBServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_NewFile(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_NewDirectory(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MetaDBServiceProcessor(boost::shared_ptr<MetaDBServiceIf> iface) :
    iface_(iface) {
    processMap_["NewFile"] = &MetaDBServiceProcessor::process_NewFile;
    processMap_["NewDirectory"] = &MetaDBServiceProcessor::process_NewDirectory;
  }

  virtual ~MetaDBServiceProcessor() {}
};

class MetaDBServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MetaDBServiceProcessorFactory(const ::boost::shared_ptr< MetaDBServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< MetaDBServiceIfFactory > handlerFactory_;
};

class MetaDBServiceMultiface : virtual public MetaDBServiceIf {
 public:
  MetaDBServiceMultiface(std::vector<boost::shared_ptr<MetaDBServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MetaDBServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<MetaDBServiceIf> > ifaces_;
  MetaDBServiceMultiface() {}
  void add(boost::shared_ptr<MetaDBServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void NewFile(const KeyInfo_THRIFT& key) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->NewFile(key);
    }
    ifaces_[i]->NewFile(key);
  }

  void NewDirectory(const KeyInfo_THRIFT& key, const int16_t zeroth_server, const int64_t inode_no) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->NewDirectory(key, zeroth_server, inode_no);
    }
    ifaces_[i]->NewDirectory(key, zeroth_server, inode_no);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class MetaDBServiceConcurrentClient : virtual public MetaDBServiceIf {
 public:
  MetaDBServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MetaDBServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void NewFile(const KeyInfo_THRIFT& key);
  int32_t send_NewFile(const KeyInfo_THRIFT& key);
  void recv_NewFile(const int32_t seqid);
  void NewDirectory(const KeyInfo_THRIFT& key, const int16_t zeroth_server, const int64_t inode_no);
  int32_t send_NewDirectory(const KeyInfo_THRIFT& key, const int16_t zeroth_server, const int64_t inode_no);
  void recv_NewDirectory(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
