/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.cmu.pdl.indexfs.srvless;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2021-11-20")
public class ServerRedirectionException extends TException implements org.apache.thrift.TBase<ServerRedirectionException, ServerRedirectionException._Fields>, java.io.Serializable, Cloneable, Comparable<ServerRedirectionException> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ServerRedirectionException");

  private static final org.apache.thrift.protocol.TField DMAP_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("dmap_data", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ServerRedirectionExceptionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ServerRedirectionExceptionTupleSchemeFactory());
  }

  public String dmap_data; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DMAP_DATA((short)1, "dmap_data");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DMAP_DATA
          return DMAP_DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DMAP_DATA, new org.apache.thrift.meta_data.FieldMetaData("dmap_data", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ServerRedirectionException.class, metaDataMap);
  }

  public ServerRedirectionException() {
  }

  public ServerRedirectionException(
    String dmap_data)
  {
    this();
    this.dmap_data = dmap_data;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ServerRedirectionException(ServerRedirectionException other) {
    if (other.isSetDmap_data()) {
      this.dmap_data = other.dmap_data;
    }
  }

  public ServerRedirectionException deepCopy() {
    return new ServerRedirectionException(this);
  }

  @Override
  public void clear() {
    this.dmap_data = null;
  }

  public String getDmap_data() {
    return this.dmap_data;
  }

  public ServerRedirectionException setDmap_data(String dmap_data) {
    this.dmap_data = dmap_data;
    return this;
  }

  public void unsetDmap_data() {
    this.dmap_data = null;
  }

  /** Returns true if field dmap_data is set (has been assigned a value) and false otherwise */
  public boolean isSetDmap_data() {
    return this.dmap_data != null;
  }

  public void setDmap_dataIsSet(boolean value) {
    if (!value) {
      this.dmap_data = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DMAP_DATA:
      if (value == null) {
        unsetDmap_data();
      } else {
        setDmap_data((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DMAP_DATA:
      return getDmap_data();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DMAP_DATA:
      return isSetDmap_data();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ServerRedirectionException)
      return this.equals((ServerRedirectionException)that);
    return false;
  }

  public boolean equals(ServerRedirectionException that) {
    if (that == null)
      return false;

    boolean this_present_dmap_data = true && this.isSetDmap_data();
    boolean that_present_dmap_data = true && that.isSetDmap_data();
    if (this_present_dmap_data || that_present_dmap_data) {
      if (!(this_present_dmap_data && that_present_dmap_data))
        return false;
      if (!this.dmap_data.equals(that.dmap_data))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_dmap_data = true && (isSetDmap_data());
    list.add(present_dmap_data);
    if (present_dmap_data)
      list.add(dmap_data);

    return list.hashCode();
  }

  @Override
  public int compareTo(ServerRedirectionException other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetDmap_data()).compareTo(other.isSetDmap_data());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDmap_data()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dmap_data, other.dmap_data);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ServerRedirectionException(");
    boolean first = true;

    sb.append("dmap_data:");
    if (this.dmap_data == null) {
      sb.append("null");
    } else {
      sb.append(this.dmap_data);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (dmap_data == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'dmap_data' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ServerRedirectionExceptionStandardSchemeFactory implements SchemeFactory {
    public ServerRedirectionExceptionStandardScheme getScheme() {
      return new ServerRedirectionExceptionStandardScheme();
    }
  }

  private static class ServerRedirectionExceptionStandardScheme extends StandardScheme<ServerRedirectionException> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ServerRedirectionException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DMAP_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.dmap_data = iprot.readString();
              struct.setDmap_dataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ServerRedirectionException struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.dmap_data != null) {
        oprot.writeFieldBegin(DMAP_DATA_FIELD_DESC);
        oprot.writeString(struct.dmap_data);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ServerRedirectionExceptionTupleSchemeFactory implements SchemeFactory {
    public ServerRedirectionExceptionTupleScheme getScheme() {
      return new ServerRedirectionExceptionTupleScheme();
    }
  }

  private static class ServerRedirectionExceptionTupleScheme extends TupleScheme<ServerRedirectionException> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ServerRedirectionException struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.dmap_data);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ServerRedirectionException struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.dmap_data = iprot.readString();
      struct.setDmap_dataIsSet(true);
    }
  }

}

